---
# comments のルール
comments:
  active: true
  #
  # UndocumentedPublicClass
  #
  # 概要
  # - コメントがないパブリッククラスを禁止する
  #
  UndocumentedPublicClass:
    active: true  # (default: false)
  #
  # UndocumentedPublicClass
  #
  # 概要
  # - コメントがないパブリックな関数を禁止する
  #
  UndocumentedPublicFunction:
    active: true  # (default: false)
  #
  # UndocumentedPublicClass
  #
  # 概要
  # - コメントがないパブリックなプロパティを禁止する
  #
  UndocumentedPublicProperty:
    active: true  # (default: false)

# style のルール
style:
  active: true
  #
  # UnusedImports
  #
  # 概要
  # - 未使用の import を禁止する
  #
  UnusedImports:
    active: true  # (default: false)
  #
  # MaxLineLength
  # 概要
  # - 1 行あたりの最大文字数
  #
  MaxLineLength:
    active: true
    excludes: ['**/test/**'] # (default: なし）
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false

# formatter のルール
formatting:
  active: true
  android: false
  autoCorrect: true
  #
  # MaximumLineLength
  # 概要
  # - 1 行あたりの最大文字数
  # - style>MaxLineLength のwrapper
  # - style>MaxLineLength を修正したとき、こちらも修正が必要
  #
  MaximumLineLength:
    active: true
    excludes: ['**/test/**'] # (default: なし）
    maxLineLength: 120
    ignoreBackTickedIdentifier: false
